### ISSUE TITLE
[Docs] - Criar WBS do projeto

### ISSUE THREAD

**Issue by GRVial** [fga-eps-mds/2024.1-PrintGo-Doc#13]
## Descrição
Precisamos criar um Work Breakdown Structure (WBS) para organizar as tarefas do nosso projeto.

## Tarefas
- [x] Identificar os principais entregáveis do projeto
- [x] Quebrar os entregáveis em tarefas menores
- [x] Organizar as tarefas em uma estrutura hierárquica
- [x] Revisar e ajustar a WBS conforme necessário

## Critérios de Aceitação
- [x] A WBS deve estar completa e revisada
