### ISSUE TITLE
[Docs] - Criar backlog

### ISSUE THREAD

**Issue by GRVial** [fga-eps-mds/2024.1-PrintGo-Doc#14]
## Descrição
Criar um backlog para o projeto contendo todas as funcionalidades e tarefas necessárias, organizadas em histórias de usuário e épicos.

## Tarefas
- [x] Configurar o ZenHub para o repositório do projeto
- [x] Identificar os principais épicos do projeto
- [x] Dividir os épicos em histórias de usuário menores
- [x] Priorizar as histórias de usuário de acordo com a importância e urgência
- [x] Documentar cada história de usuário com critérios de aceitação claros
- [x] Prototipar as histórias de usuário

## Critérios de Aceitação
- [x] O backlog deve conter todos os épicos e histórias de usuário necessárias
- [x] Cada história de usuário deve ter uma descrição clara e critérios de aceitação
- [x] O protótipo deve representar a história de usuário selecionada com precisão

## Formato de Histórias de Usuário
Como [tipo de usuário], eu quero [realizar alguma ação] para [alcançar algum objetivo].

## Exemplo de História de Usuário
**Título**: Cadastro de Novo Usuário
**Descrição**: Como usuário novo, eu quero me cadastrar no sistema para acessar suas funcionalidades.
**Critérios de Aceitação**:
- O formulário de cadastro deve conter campos para nome, e-mail e senha.
- O sistema deve validar o e-mail e a senha.
- Após o cadastro, o usuário deve receber um e-mail de confirmação.

**Comment by DanielViniciusAlves** [comment]
Comecei a desenvolver o Backlog com o @GRVial

**Comment by DanielViniciusAlves** [comment]
Foram feitos os épicos, as histórias de usuário e configuração do ZenHub. Falta criar o protótipo das issues, a prioridade é de fazer o protótipos das seguintes issues:

- [ ] #28  @GustavoHaubert 
- [ ] #23  @anajbsouza 
- [ ] #40 @caiolamego 

Exemplo:

Documentação - https://www.figma.com/design/vHhS5dqVvmexAEuD8Y39SP/ConecteSus?node-id=0-1&t=s2OmWWH36quZgPc0-1

Protótipo - https://www.figma.com/proto/vHhS5dqVvmexAEuD8Y39SP/ConecteSus?node-id=2-4&t=Qj3B0qki2teRmem9-1&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=1%3A2

Protótipo semestre anterior - https://www.figma.com/file/NELNdbY5Mc8WJl8US3gNr7/printGo?type=design&node-id=0-1&mode=design&t=zqD555P2JbtSscOv-0

**Comment by GustavoHaubert** [comment]
Foram feitos os épicos, as histórias de usuário e configuração do ZenHub. Falta criar o protótipo das issues, a prioridade é de fazer o protótipos das seguintes issues:

 https://github.com/fga-eps-mds/2024.1-PrintGo-Doc/issues/28 @GustavoHaubert 
 https://github.com/fga-eps-mds/2024.1-PrintGo-Doc/issues/23 @anajbsouza 
 https://github.com/fga-eps-mds/2024.1-PrintGo-Doc/issues/40 @caiolamego
Exemplo:

Documentação - https://www.figma.com/design/vHhS5dqVvmexAEuD8Y39SP/ConecteSus?node-id=0-1&t=s2OmWWH36quZgPc0-1

Protótipo - https://www.figma.com/proto/vHhS5dqVvmexAEuD8Y39SP/ConecteSus?node-id=2-4&t=Qj3B0qki2teRmem9-1&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=1%3A2

Protótipo semestre anterior - https://www.figma.com/file/NELNdbY5Mc8WJl8US3gNr7/printGo?type=design&node-id=0-1&mode=design&t=zqD555P2JbtSscOv-0

**Comment by caiolamego** [comment]
Protótipo da US10 - DASHBOARD INTERATIVO: https://www.figma.com/proto/P1UAiqzvqVD6Uek5mMJoED/US10?node-id=54-2500&t=yMbbnWTxH4FYlK2x-1&scaling=contain&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=26%3A2894

**Comment by caiolamego** [comment]
Protótipo US10 -DASHBOARD INTERATIVO: https://www.figma.com/proto/P1UAiqzvqVD6Uek5mMJoED/US10?node-id=26-2894&t=QFtKfdsYz19LV86c-1&scaling=contain&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=26%3A2894

Fiz um fluxo simulando o usuário clicando e selecionando os três tipos de filtros determinados na US.
Se precisar mudar alguma coisa me avisem prfvr

**Comment by GustavoHaubert** [comment]
Protótipo US 03 - Gestão de equipamentos: https://www.figma.com/proto/nMiS0y8QcqYYUm4kV6CXba/prototipo-printGo?node-id=84-2545&t=QEnwk3AN26ZcbV5D-0&scaling=contain&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=84%3A2545

Fiz um fluxo simulando o usuário clicando em cadastrar e acessar lista de equipamentos.

**Comment by caiolamego** [comment]
Atualizei minha história para US9
