### ISSUE TITLE
US 01 - Gerenciamento de Contratos

### ISSUE THREAD

**Issue by DanielViniciusAlves** [fga-eps-mds/2024.1-PrintGo-Doc#23]
**Título**: Gerenciamento de Contratos

**Descrição**: Como servidor da PCGO da área administrativa, eu quero cadastrar, listar, atualizar e remover contratos relacionados a cada equipamento para gerenciar acordos.

**Critérios de Aceitação**:

### **O formulário de cadastro deve conter os campos:**

- [ ] numero do contrato: alfanumérico [Obrigatório];
- [ ] gestor do contrato: texto [obrigatório]
- [ ] descrição (processo): texto [obrigatório]
- [ ] data de início e data de término: data [obrigatório].

### **Outros critérios:**

- [ ] Haverá um campo "status", que a partir da data de inicio do contrato ele ficara ativo (esse campo não aparece no cadastro, apenas na listagem e na edição).
- [ ] O campo "status" devera ficar inativo automaticamente, antes da data de inicio e após a data de termino.
- [ ] O sistema deve validar que todos os campos obrigatórios estão preenchidos.
- [ ] O sistema deve permitir a edição dos campos de número do contrato, gestor do contrato, descrição (processo), data de início, data de término e status.
- [ ] O sistema deve permitir a desativação e ativação de contratos.
- [ ] Após o cadastro, o contrato deve aparecer na lista de contratos disponíveis.
- [ ] Após a edição ou desativação, a lista de contratos deve ser atualizada automaticamente.
- [ ] Caso a data de término seja alterada o "status" também podera ser alterado dependendo da nova data informada.

**Protótipo**:

Imagens do protótipo desenvolvido por @anajbsouza :

![Cadastro de Contratos](https://github.com/user-attachments/assets/befa5007-bdaa-46b4-8a7b-1e72c3934ea6)
![Campos Obrigatórios](https://github.com/user-attachments/assets/bfa63373-5f37-4913-b743-0a12352a583c)
![Contratos Disponiveis](https://github.com/user-attachments/assets/5d8b7b77-d6e8-4cb1-948e-c9d9ef204a79)
![Edição de Contrato](https://github.com/user-attachments/assets/e1d35495-5557-4c79-81ed-d5a78aa105fe)
![Visualização de Contrato](https://github.com/user-attachments/assets/bb4cb8d3-aa0d-4863-a95b-5751e9c30204)
