### ISSUE TITLE
US 03 - Gerenciamento de Equipamentos

### ISSUE THREAD

**Issue by DanielViniciusAlves** [fga-eps-mds/2024.1-PrintGo-Doc#28]
**Título**: Gerenciamento de Equipamentos

**Descrição**: Como servidor da PCGO da área administrativa, eu quero cadastrar, listar, atualizar e remover equipamentos para acompanhar os recursos disponíveis.

**Critérios de Aceitação**:

### **O formulário de cadastro deve conter os campos:**

- [ ] numero do contrato: seleção [Obrigatório];
- [ ] marca: seleção [Obrigatório]; 
- [ ] modelo: seleção [Obrigatório];
- [ ] endereço ip: mascara de ip [Obrigatório];
- [ ] número de série [Obrigatório];
- [ ] localização (Schedula) [Obrigatório];
- [ ] data de instalação [Obrigatório];  
- [ ] contador de instalação: número (maior igual a 0) [Obrigatório]; -> contagem de impressão no momento da instalação
- [ ] data de retirada: [Obrigatório]; 
- [ ] contador de retirada: número (maior igual a 0) [Obrigatório], 
- [ ] equipamento fora da rede: checkbox [Obrigatório];
- [ ] status (ativo/inativo): [Obrigatório].

### **Outros critérios:**

- [ ] Ao cadastrar o contador de instalação ele será o contador atual;
- [ ] Caso o modelo do equipamento seja colorido, os campos de contador (instalação, atual e retirada) deverá ter os contadores preto e branco e colorido.
- [ ] Se o equipamento estiver fora rede, automaticamente o ip é 0.
- [ ] Validação de mascara para o endereço ip.
- [ ] O sistema deve validar que todos os campos obrigatórios estão preenchidos.
- [ ] O sistema deve permitir a edição dos campos de todos os campos.
- [ ] O sistema deve permitir a ativação ou desativação de equipamentos.
- [ ] Caso a data de retirada esteja preenchida, o "status" automaticamente ficara inativo.
- [ ] Após o cadastro, o equipamento deve aparecer na lista de equipamentos disponíveis.
- [ ] Após a edição ou exclusão, a lista de equipamentos deve ser atualizada automaticamente.

- [ ] Ao visualizar os equipamentos deverão aparecer os dados (base de dados do modelo):  
- Último contador (contador atual ou de retirada);
- data último contador;
- versão do firmware;
- tempo ativo;
- total de digitalizações (SNMP);
- total de cópias preto e branco (SNMP);
- total de cópias coloridas (caso seja colorida) (SNMP);
- total geral (total de copias coloridas + copias preto e branco).

**Protótipo**:

![image](https://github.com/user-attachments/assets/2ffcb513-78a5-4580-acf5-4e3981292af7)

![image](https://github.com/user-attachments/assets/5e2aef2b-00e1-4c49-8814-23ed994c16f9)

![image](https://github.com/user-attachments/assets/53c3a3f4-3318-4323-a0dc-423ad959c908)

![image](https://github.com/user-attachments/assets/68260f9e-2454-4a6a-95de-da63aa3bd2a1)

Protótipo [disponível aqui](https://www.figma.com/proto/gy1Y7e6FvyasuVFgEUD1xD/US03?t=S4pHFvy3tSrNtkNz-1), desenvolvido por @DanielViniciusAlves e @GustavoHaubert.

**Comment by GustavoHaubert** [comment]
**Protótipo:**

Link do protótipo atualizado com update e delete da US 03: https://www.figma.com/proto/nMiS0y8QcqYYUm4kV6CXba/prototipo-printGo?node-id=84-2545&t=i5wAH42hY1sFxsOz-0&scaling=contain&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=84%3A2545
