### ISSUE TITLE
US 04 - Cadastro de Localidade dos Equipamentos

### ISSUE THREAD

**Issue by DanielViniciusAlves** [fga-eps-mds/2024.1-PrintGo-Doc#34]
**Título**: Cadastro de Localidade dos Equipamentos

**Descrição**: Como servidor da PCGO da área administrativa, eu quero cadastrar a localidade dos equipamentos para saber onde cada um está localizado.  

**Critérios de Aceitação**:

- [ ] O formulário de cadastro deve conter campos para o endereço, cidade, estado e CEP.
- [ ] O sistema deve validar que todos os campos obrigatórios estão preenchidos.
- [ ] A localidade deve ser associada corretamente ao equipamento.
