### ISSUE TITLE
US 05 - Regístro Manual de Contagem de Impressões

### ISSUE THREAD

**Issue by DanielViniciusAlves** [fga-eps-mds/2024.1-PrintGo-Doc#36]
**Título**: Registro Manual de Contagem de Impressões  
**Descrição**: Como servidor da PCGO da unidade policial, eu quero salvar dados de contagem manual para registrar as impressões realizadas.  
**Critérios de Aceitação**:
- [ ] O formulário de registro deve conter campos para o número de impressões, data e equipamento associado;
- [ ] Deve ser possivel buscar o equipamento associado de acordo com sua localização (Cidade, Regional, Unidade);
- [ ] O sistema deve validar que todos os campos obrigatórios estão preenchidos;
- [ ] Após o registro, os dados devem ser salvos e disponíveis para consulta;

**Protótipo**:

**Pagina de registro manual de contador de impressão**

![image](https://github.com/user-attachments/assets/a8286758-4043-417f-94d2-866eb076ce45)

Os protótipos foram desenvolvidos por @MatheussBrant
