### ISSUE TITLE
US 06 - Registro Automático de Contagem de Impressões

### ISSUE THREAD

**Issue by DanielViniciusAlves** [fga-eps-mds/2024.1-PrintGo-Doc#37]
**Título**: Registro Automático de Contagem de Impressões  
**Descrição**: Como sistema do PrintGO, eu quero salvar dados de contagem automática para monitorar impressões sem intervenção manual.  
**Critérios de Aceitação**:
- [ ] O sistema deve ser capaz de capturar automaticamente o número de impressões de cada equipamento usando SNMP.
- [ ] Os dados capturados devem ser armazenados corretamente e disponíveis para consulta.
- [ ] Utilizar os OIDs registrados no padrão de equipamento na coleta.
- [ ] A coleta deve rodar periodicamente.
- [ ] Rotina de registros deve ser personalizável, podendo escolher a data e horário.
- [ ] A área para definir a rotina aparecerá de acordo com a opção escolhida no dropbox "Rotina de Registro"
- [ ] O registro pode ser executado por grupo de equipamentos conforme centro de gestão cidade, regional ou subposto de trabalho (do Schedula).
- [ ] A rotina semanal deve ter a opção de ser feita em um dia ou mais da semana.
- [ ] A rotina diária deve ter a opção de ser feita de forma intervalada.
- [ ] Deve ser possível definir a rotina de todas as regionais de uma vez, através de uma opção no dropbox.

![image](https://github.com/user-attachments/assets/0b3aa2f1-ba74-4e32-8b41-305071a40fb5)
