### ISSUE TITLE
US 07 - Comparação de Impressões Mensais

### ISSUE THREAD

**Issue by DanielViniciusAlves** [fga-eps-mds/2024.1-PrintGo-Doc#38]
**Título**: Comparação de Impressões Mensais  
**Descrição**: Como servidor da PCGO da área administrativa e unidade policial, eu quero comparar as impressões feitas com o mês anterior para analisar o uso.

**Critérios de Aceitação**:
- [ ] O sistema deve gerar relatórios comparativos entre data de geração deste e do relatório do mês anterior.
- [ ] Campos necessários:
- [ ] 1. Numero de serie;
- [ ] 2. Cidade, regional, unidade;
- [ ] 3. Contador do ultimo faturamento (mes passado) (preto e branco e colorido);
- [ ] 3. Contador atual (preto e branco e colorido);
- [ ] 4. Total de cópias (Diferença entre o contador do ultimo faturamento e do contador atual);
- [ ] O relatório deve destacar aumentos ou diminuições no número de impressões.
- [ ] O sistema deve permitir gerar relatórios todos os dias.
- [ ] O sistema deve atualizar o relatório do mês a cada 30 dias (mesmo que a impressora esteja inativa).
- [ ] O contador da data do relatório será sempre o contador atual da impressora menos o contador do mês anterior (última relatório mensal).
- [ ] O relatório deve ser exportável em formato PDF.
- [ ] O relatório de faturamento deve ser exportado em formato Excel;
- [ ] A data do relatório na página de visualização de equipamento será sempre a data do relatório que foi gerado no mês atual.
- [ ] Na página de Auditoria deverá ser possível selecionar o contrato para listar os equipamentos contidos nele.
- [ ] Quando o contrato for selecionado, o botão de gerar relatório do contrato ficará ativo e ao clicar nele será gerado um relatório do contrato.
- [ ] Em cada linha da listagem de equipamentos haverá distribuídos em colunas o nome do equipamento, contador atual do PrintGO, contador atual da locadora, total de impressões do PrintGO, total de impressões locadora e um botão de gerar relatório.
- [ ] Se algum dado do PrintGO estiver diferente do dado informado pela locadora, esses dados ficaram em vermelho para destacá-los.
- [ ] Deve ser possível alterar a margem de erro
- [ ] O sistema deve permitir fazer o upload do relatório da locadora para realizar o comparativo

**Protótipo**:
https://www.figma.com/proto/c3qzfIRFDcwnzqsspaBbYr/US07?node-id=0-1&t=L4j0y5cCLBsB1fXo-0&scaling=contain&content-scaling=fixed&starting-point-node-id=4004%3A365&show-proto-sidebar=1

![Tela de auditoria (1)](https://github.com/user-attachments/assets/1ccbcc05-3f22-4549-af3d-5ed716f88ed4)

![Tela de upload em auditoria](https://github.com/user-attachments/assets/623beb8a-072f-4990-a268-6034bc672c3f)

![Tela de auditoria com equipamentos listados (1)](https://github.com/user-attachments/assets/af252399-178b-4ca8-8a68-32c54aeecfad)

![Vizualizar equipamento](https://github.com/user-attachments/assets/a4a472b8-0495-4d3b-a78b-faba004fe841)

![Screenshot from 2024-08-19 14-30-28](https://github.com/user-attachments/assets/d6f811b0-2a38-4b12-bf1e-109185646d54)
