### ISSUE TITLE
US 08 - Geração de Relatório de Faturamento

### ISSUE THREAD

**Issue by DanielViniciusAlves** [fga-eps-mds/2024.1-PrintGo-Doc#39]
**Título**: Geração de Relatório de Faturamento

**Descrição**: Como servidor da PCGO da área administrativa e unidade policial, eu quero gerar relatórios para analisar dados de faturamento.

**Critérios de Aceitação**:

- [ ] O sistema deve permitir a geração de relatórios de faturamento.
- [ ] Os relatórios devem ser exportáveis em formato Excel.
- [ ] Os relatórios devem incluir gráficos e tabelas para facilitar a análise dos dados.
- [ ] Campos necessários:
- [ ] 1. Numero de serie;
- [ ] 2. Cidade, regional, unidade;
- [ ] 3. Contador do ultimo faturamento (mes passado) (preto e branco e colorido);
- [ ] 3. Contador atual (preto e branco e colorido);
- [ ] 4. Total de cópias (Diferença entre o contador do ultimo faturamento e do contador atual);

**Comment by eliseukadesh67** [comment]
Essa história será fechada porque foi entendido que ela faz parte da [US07](#38)
