### ISSUE TITLE
US 09 - Dashboard Interativo

### ISSUE THREAD

**Issue by DanielViniciusAlves** [fga-eps-mds/2024.1-PrintGo-Doc#40]
**Título**: Dashboard Interativo

**Descrição**: Como servidor da PCGO da área administrativa e unidade policial, eu quero um dashboard interativo para visualizar dados em tempo real e tomar decisões informadas.  

**Critérios de Aceitação**:

- [ ] O dashboard deve apresentar gráficos interativos com dados de quantidade de impressões coloridas e preto e branco e de equipamentos coloridos e preto e branco;
- [ ] O usuário deve poder filtrar os dados por período e localidade.
- [ ] O dashboard deve ser atualizado com os dados mais recentes.

**Protótipo**:

![Screenshot from 2024-08-28 10-17-24](https://github.com/user-attachments/assets/537d4616-2d3f-4521-a937-fe5a6ab80761)

Link do protótipo desenvolvido por @caiolamego: https://www.figma.com/design/nMiS0y8QcqYYUm4kV6CXba/prototipo-printGo?node-id=0-1&t=ubwd8G4hg0ujb5On-0
