### ISSUE TITLE
US 10 - Controle de Insumos

### ISSUE THREAD

**Issue by DanielViniciusAlves** [fga-eps-mds/2024.1-PrintGo-Doc#41]
**Título**: Controle de Insumos  
**Descrição**: Como servidor da PCGO da área administrativa e unidade policial, eu quero controlar insumos (como papel e toner) para garantir que sempre haja material disponível.  
**Critérios de Aceitação**:
- [ ] O sistema deve permitir o registro de entradas e saídas de insumos.
- [ ] O sistema deve alertar o administrador quando os níveis de insumos estiverem baixos.
- [ ] O histórico de consumo de insumos deve estar disponível para consulta.
