### ISSUE TITLE
US 11 - Gerenciamento de Chamados

### ISSUE THREAD

**Issue by DanielViniciusAlves** [fga-eps-mds/2024.1-PrintGo-Doc#42]
**Título**: Criação e Gerenciamento de Chamados  
**Descrição**: Como servidor da PCGO da área administrativa e unidade policial, eu quero criar e gerenciar chamados para solicitar suporte ou manutenção.  
**Critérios de Aceitação**:
- [ ] O formulário de criação de chamados deve conter campos para descrição do problema, prioridade e equipamento associado.
- [ ] O sistema deve permitir a atualização do status dos chamados.
- [ ] Os usuários devem poder consultar o histórico de chamados abertos e fechados.
