### ISSUE TITLE
US 12 - Notificações de Chamados por Email

### ISSUE THREAD

**Issue by DanielViniciusAlves** [fga-eps-mds/2024.1-PrintGo-Doc#43]
**Título**: Notificações de Chamados por Email  
**Descrição**: Como servidor da PCGO da área administrativa, eu quero receber avisos de chamados por email para ser notificado sobre atualizações e resoluções.  
**Critérios de Aceitação**:
- [ ] O sistema deve enviar notificações por email quando um chamado for criado, atualizado ou resolvido.
- [ ] As notificações por email devem incluir detalhes do chamado, como descrição, status e equipamento associado.
- [ ] O usuário deve poder configurar as preferências de notificação por email.
