### ISSUE TITLE
US 13 - Controle de Perfis de Usuários

### ISSUE THREAD

**Issue by DanielViniciusAlves** [fga-eps-mds/2024.1-PrintGo-Doc#44]
**Título**: Controle de Perfis de Usuários  
**Descrição**: Como servidor da PCGO da área administrativa, eu quero controlar os perfis de usuários para definir permissões e acesso.  
**Critérios de Aceitação**:
- [ ] O sistema deve permitir a criação e edição de perfis de usuários com diferentes níveis de acesso.
- [ ] O sistema deve garantir que apenas usuários autorizados possam acessar determinadas funcionalidades.
- [ ] O administrador deve poder desativar e reativar contas de usuários.
