### ISSUE TITLE
US 14 - Autenticação de Usuários

### ISSUE THREAD

**Issue by DanielViniciusAlves** [fga-eps-mds/2024.1-PrintGo-Doc#45]
**Título**: Autenticação de Usuários  
**Descrição**: Como usuário do PrintGO, eu quero me autenticar no sistema para acessar funcionalidades de acordo com meu perfil.  
**Critérios de Aceitação**:
- [ ] O sistema deve permitir o login com email e senha.
- [ ] O sistema deve validar as credenciais do usuário e permitir o acesso apenas para usuários autenticados.
- [ ] O usuário deve poder redefinir a senha caso a esqueça.
