### ISSUE TITLE
US 15 - Registro de Localidade das Impressões

### ISSUE THREAD

**Issue by DanielViniciusAlves** [fga-eps-mds/2024.1-PrintGo-Doc#46]
**Título**: Registro de Localidade das Impressões  
**Descrição**: Como servidor da PCGO da área administrativa, eu quero registrar onde foram realizadas impressões para ter um histórico detalhado de uso por localidade.  
**Critérios de Aceitação**:
- [ ] O sistema deve registrar a localidade de cada impressão realizada.
- [ ] O administrador deve poder consultar o histórico de impressões por localidade.
- [ ] O relatório de impressões por localidade deve ser exportável em formato PDF ou Excel.
