### ISSUE TITLE
US 16 - Gerenciamento de padrão de equipamentos

### ISSUE THREAD

**Issue by eliseukadesh67** [fga-eps-mds/2024.1-PrintGo-Doc#66]
**Título**: Gerenciamento e padrão de equipamentos

**Descrição**: Como servidor da PCGO da área administrativa, eu quero cadastrar, listar, atualizar e remover modelos de equipamentos para ter controle dos modelos de equipamentos disponíveis.

**Critérios de Aceitação**:

**O cadastro de modelos devem possuir os campos**:
- [x] Marca;
- [x] Modelo;
- [x] Tipo (multifuncional laser Monocromático / multifuncional laser colorido / Scanner);
- [x] Contador color (indicador de que o equipamento possui contador color);
- [x] (Códigos OId de correspondência na tabela MIB de cada equipamento):
- [x] OId Modelo (Não obrigatorio);
- [x] OId Número de série (Não obrigatorio);
- [x] OId Versão do firmware (Não obrigatorio);
- [x] OId Tempo ativo (Não obrigatorio);
- [x] OId Total de digitalizações (Não obrigatorio);
- [x] OId Total de cópias preto e branco (Não obrigatorio);
- [x] OId Total de cópias coloridas (Não obrigatorio);
- [x] OId Total geral (Não obrigatorio);

### **Outros critérios:**

- [x] O sistema deve validar que todos os campos obrigatórios estão preenchidos.
- [x] O sistema deve permitir a edição dos campos de todos os campos.
- [x] Após o cadastro, o modelo equipamento deve aparecer na lista de modelos de equipamentos disponíveis.
- [x] Após a edição ou exclusão, a lista de modelos de equipamentos deve ser atualizada automaticamente.

Tela de Cadastro de padões:
![image](https://github.com/user-attachments/assets/fcdf1fe3-79bc-46df-81f3-2649e62a2c03)

Tela de Listagem de padões
![image](https://github.com/user-attachments/assets/67486df4-4069-4fe1-8e12-aa44cc8baec2)

Tela de visualização de padrões
![image](https://github.com/user-attachments/assets/7e00723c-0938-4e3d-911c-6c1c33d3111a)

Tela de edição de padões
![image](https://github.com/user-attachments/assets/5e0ceda1-be85-405c-b176-87c74d07cdf9)
